spring.application.name=leave_application_processing_system

# Disable management context to avoid circular server.port reference in WAR deployment
management.server.port=

# To use DataInitializer
spring.jpa.defer-datasource-initialization=false

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Recreate database on every start
spring.jpa.hibernate.ddl-auto=create-drop

# Show the SQL in console
spring.jpa.show-sql=true

# Set timeout to 30 minutes
server.servlet.session.timeout=30m